version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
   volumes:
     - ./esdata:/usr/share/elasticsearch/data   
   container_name: elasticsearch
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
     
  kibana:
   image: docker.elastic.co/kibana/kibana:7.6.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    ports: 
     - "5000:5000"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config-dir:/usr/share/logstash/pipeline/
    environment:
      - xpack.monitoring.enabled:true
      - xpack.monitoring.elasticsearch.url:http://localhost:9200
    
volumes:
  esdata: